version: "3.5"

services:
  api01: &api
    image: ghcr.io/elixiremfoco/rinha-backend-2024-q1:latest
    hostname: api01
    environment:
      - PHX_HOST=api01
      - SECRET_KEY_BASE=HScbRLB0u8vOQAMWLC2DFHdrpnMKcGEs
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/rinha
      - IP_V4_ADDRESS=192.0.1.11
      - IP_NODE=192.0.1.12
    
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"
    networks:
      erlcluster:
        ipv4_address: 192.0.1.11

  api02:
    <<: *api 
    hostname: api02
    environment:
      - PORT=4001
      - PHX_HOST=api02
      - SECRET_KEY_BASE=ZufWuBc1xg3ssETNHHB14bZ1PKM1mruC
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/rinha
      - IP_V4_ADDRESS=192.0.1.12
      - IP_NODE=192.0.1.11
    ports:
      - "4001:4001"
    networks:
      erlcluster:
        ipv4_address: 192.0.1.12
 
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"
    networks:
      erlcluster:
        ipv4_address: 192.0.1.13

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./confs/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./confs/postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d rinha" ]
      interval: 4s
      timeout: 2s
      retries: 5
    networks:
      erlcluster:
        ipv4_address: 192.0.1.14

networks:
  erlcluster:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.0.1.0/24"
